# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the terms described in the LICENSE file in
# the root directory of this source tree.

# Import routes to trigger router registration
from . import routes  # noqa: F401
from .agents_service import AgentsService
from .models import (
    Agent,
    AgentConfig,
    AgentConfigCommon,
    AgentConfigOverridablePerTurn,
    AgentCreateResponse,
    AgentSessionCreateResponse,
    AgentStepResponse,
    AgentToolGroup,
    AgentToolGroupWithArgs,
    AgentTurnCreateRequest,
    AgentTurnResponseEvent,
    AgentTurnResponseEventPayload,
    AgentTurnResponseEventType,
    AgentTurnResponseStepCompletePayload,
    AgentTurnResponseStepProgressPayload,
    AgentTurnResponseStepStartPayload,
    AgentTurnResponseStreamChunk,
    AgentTurnResponseTurnAwaitingInputPayload,
    AgentTurnResponseTurnCompletePayload,
    AgentTurnResponseTurnStartPayload,
    AgentTurnResumeRequest,
    Attachment,
    CreateAgentSessionRequest,
    CreateOpenAIResponseRequest,
    Document,
    InferenceStep,
    MemoryRetrievalStep,
    ResponseGuardrail,
    ResponseGuardrailSpec,
    Session,
    ShieldCallStep,
    Step,
    StepCommon,
    StepType,
    ToolExecutionStep,
    Turn,
)
from .openai_responses import (
    ListOpenAIResponseInputItem,
    ListOpenAIResponseObject,
    OpenAIDeleteResponseObject,
    OpenAIResponseInput,
    OpenAIResponseInputTool,
    OpenAIResponseObject,
    OpenAIResponseObjectStream,
    OpenAIResponsePrompt,
    OpenAIResponseText,
)

# Backward compatibility - export Agents as alias for AgentsService
Agents = AgentsService

__all__ = [
    "Agents",
    "AgentsService",
    "Agent",
    "AgentConfig",
    "AgentConfigCommon",
    "AgentConfigOverridablePerTurn",
    "AgentCreateResponse",
    "AgentSessionCreateResponse",
    "AgentStepResponse",
    "AgentToolGroup",
    "AgentToolGroupWithArgs",
    "AgentTurnCreateRequest",
    "AgentTurnResumeRequest",
    "AgentTurnResponseEvent",
    "AgentTurnResponseEventPayload",
    "AgentTurnResponseEventType",
    "AgentTurnResponseStepCompletePayload",
    "AgentTurnResponseStepProgressPayload",
    "AgentTurnResponseStepStartPayload",
    "AgentTurnResponseStreamChunk",
    "AgentTurnResponseTurnAwaitingInputPayload",
    "AgentTurnResponseTurnCompletePayload",
    "AgentTurnResponseTurnStartPayload",
    "Attachment",
    "CreateAgentSessionRequest",
    "CreateOpenAIResponseRequest",
    "Document",
    "InferenceStep",
    "MemoryRetrievalStep",
    "ResponseGuardrail",
    "ResponseGuardrailSpec",
    "Session",
    "ShieldCallStep",
    "Step",
    "StepCommon",
    "StepType",
    "ToolExecutionStep",
    "Turn",
    "ListOpenAIResponseInputItem",
    "ListOpenAIResponseObject",
    "OpenAIDeleteResponseObject",
    "OpenAIResponseInput",
    "OpenAIResponseInputTool",
    "OpenAIResponseObject",
    "OpenAIResponseObjectStream",
    "OpenAIResponsePrompt",
    "OpenAIResponseText",
]
