# GitHub Dependabot configuration
version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Will use the default workflow location of `.github/workflows`
    schedule:
      interval: "weekly"
      day: "saturday"
    commit-message:
      prefix: chore(github-deps)
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
      - type/dependencies
      - python
    commit-message:
      prefix: chore(python-deps)
