# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the terms described in the LICENSE file in
# the root directory of this source tree.

# Import routes to trigger router registration
from llama_stack.apis.common.content_types import InterleavedContent
from llama_stack.apis.common.responses import Order
from llama_stack.models.llama.datatypes import BuiltinTool, StopReason, ToolCall, ToolDefinition, ToolPromptFormat

from . import routes  # noqa: F401
from .inference_service import InferenceService
from .models import (
    Bf16QuantizationConfig,
    ChatCompletionRequest,
    ChatCompletionResponse,
    ChatCompletionResponseEvent,
    ChatCompletionResponseEventType,
    ChatCompletionResponseStreamChunk,
    CompletionMessage,
    CompletionRequest,
    CompletionResponse,
    CompletionResponseStreamChunk,
    EmbeddingsResponse,
    EmbeddingTaskType,
    Fp8QuantizationConfig,
    GrammarResponseFormat,
    GreedySamplingStrategy,
    Int4QuantizationConfig,
    JsonSchemaResponseFormat,
    ListOpenAIChatCompletionResponse,
    LogProbConfig,
    Message,
    ModelStore,
    OpenAIAssistantMessageParam,
    OpenAIChatCompletion,
    OpenAIChatCompletionChunk,
    OpenAIChatCompletionContentPartImageParam,
    OpenAIChatCompletionContentPartParam,
    OpenAIChatCompletionContentPartTextParam,
    OpenAIChatCompletionMessageContent,
    OpenAIChatCompletionRequestWithExtraBody,
    OpenAIChatCompletionTextOnlyMessageContent,
    OpenAIChatCompletionToolCall,
    OpenAIChatCompletionToolCallFunction,
    OpenAIChatCompletionUsage,
    OpenAIChatCompletionUsageCompletionTokensDetails,
    OpenAIChatCompletionUsagePromptTokensDetails,
    OpenAIChoice,
    OpenAIChoiceDelta,
    OpenAIChoiceLogprobs,
    OpenAIChunkChoice,
    OpenAICompletion,
    OpenAICompletionChoice,
    OpenAICompletionLogprobs,
    OpenAICompletionRequestWithExtraBody,
    OpenAICompletionWithInputMessages,
    OpenAIDeveloperMessageParam,
    OpenAIEmbeddingData,
    OpenAIEmbeddingsRequestWithExtraBody,
    OpenAIEmbeddingsResponse,
    OpenAIEmbeddingUsage,
    OpenAIFile,
    OpenAIFileFile,
    OpenAIImageURL,
    OpenAIJSONSchema,
    OpenAIMessageParam,
    OpenAIResponseFormatJSONObject,
    OpenAIResponseFormatJSONSchema,
    OpenAIResponseFormatParam,
    OpenAIResponseFormatText,
    OpenAISystemMessageParam,
    OpenAITokenLogProb,
    OpenAIToolMessageParam,
    OpenAITopLogProb,
    OpenAIUserMessageParam,
    QuantizationConfig,
    QuantizationType,
    RerankData,
    RerankResponse,
    ResponseFormat,
    ResponseFormatType,
    SamplingParams,
    SamplingStrategy,
    SystemMessage,
    SystemMessageBehavior,
    TextTruncation,
    TokenLogProbs,
    ToolChoice,
    ToolConfig,
    ToolResponse,
    ToolResponseMessage,
    TopKSamplingStrategy,
    TopPSamplingStrategy,
    UserMessage,
)

# Backward compatibility - export Inference as alias for InferenceService
Inference = InferenceService
InferenceProvider = InferenceService

__all__ = [
    "Inference",
    "InferenceProvider",
    "InferenceService",
    "InterleavedContent",
    "ModelStore",
    "Order",
    # Sampling
    "SamplingParams",
    "SamplingStrategy",
    "GreedySamplingStrategy",
    "TopPSamplingStrategy",
    "TopKSamplingStrategy",
    # Quantization
    "QuantizationConfig",
    "QuantizationType",
    "Bf16QuantizationConfig",
    "Fp8QuantizationConfig",
    "Int4QuantizationConfig",
    # Messages
    "Message",
    "UserMessage",
    "SystemMessage",
    "ToolResponseMessage",
    "CompletionMessage",
    # Tools
    "BuiltinTool",
    "ToolCall",
    "ToolChoice",
    "ToolConfig",
    "ToolDefinition",
    "ToolPromptFormat",
    "ToolResponse",
    # StopReason
    "StopReason",
    # Completion
    "CompletionRequest",
    "CompletionResponse",
    "CompletionResponseStreamChunk",
    # Chat Completion
    "ChatCompletionRequest",
    "ChatCompletionResponse",
    "ChatCompletionResponseStreamChunk",
    "ChatCompletionResponseEvent",
    "ChatCompletionResponseEventType",
    # Embeddings
    "EmbeddingsResponse",
    "EmbeddingTaskType",
    "TextTruncation",
    # Rerank
    "RerankResponse",
    "RerankData",
    # Response Format
    "ResponseFormat",
    "ResponseFormatType",
    "JsonSchemaResponseFormat",
    "GrammarResponseFormat",
    # Log Probs
    "LogProbConfig",
    "TokenLogProbs",
    # System Message Behavior
    "SystemMessageBehavior",
    # OpenAI Models
    "OpenAICompletion",
    "OpenAICompletionRequestWithExtraBody",
    "OpenAICompletionChoice",
    "OpenAICompletionLogprobs",
    "OpenAIChatCompletion",
    "OpenAIChatCompletionRequestWithExtraBody",
    "OpenAIChatCompletionChunk",
    "OpenAIChatCompletionUsage",
    "OpenAIChatCompletionUsageCompletionTokensDetails",
    "OpenAIChatCompletionUsagePromptTokensDetails",
    "OpenAIChoice",
    "OpenAIChoiceDelta",
    "OpenAIChoiceLogprobs",
    "OpenAIChunkChoice",
    "OpenAIMessageParam",
    "OpenAIUserMessageParam",
    "OpenAISystemMessageParam",
    "OpenAIAssistantMessageParam",
    "OpenAIToolMessageParam",
    "OpenAIDeveloperMessageParam",
    "OpenAIChatCompletionContentPartParam",
    "OpenAIChatCompletionContentPartTextParam",
    "OpenAIChatCompletionContentPartImageParam",
    "OpenAIChatCompletionMessageContent",
    "OpenAIChatCompletionTextOnlyMessageContent",
    "OpenAIChatCompletionToolCall",
    "OpenAIChatCompletionToolCallFunction",
    "OpenAIEmbeddingsRequestWithExtraBody",
    "OpenAIEmbeddingsResponse",
    "OpenAIEmbeddingData",
    "OpenAIEmbeddingUsage",
    "OpenAIResponseFormatParam",
    "OpenAIResponseFormatText",
    "OpenAIResponseFormatJSONSchema",
    "OpenAIResponseFormatJSONObject",
    "OpenAIJSONSchema",
    "OpenAIImageURL",
    "OpenAIFile",
    "OpenAIFileFile",
    "OpenAITokenLogProb",
    "OpenAITopLogProb",
    "OpenAICompletionWithInputMessages",
    "ListOpenAIChatCompletionResponse",
]
