version: '2'
distribution_spec:
  description: Distribution for running open benchmarks
  providers:
    inference:
    - remote::openai
    - remote::anthropic
    - remote::gemini
    - remote::groq
    - remote::together
    vector_io:
    - inline::sqlite-vec
    - remote::chromadb
    - remote::pgvector
    safety:
    - inline::llama-guard
    agents:
    - inline::meta-reference
    telemetry:
    - inline::meta-reference
    datasetio:
    - remote::huggingface
    - inline::localfs
    tool_runtime:
    - remote::brave-search
    - remote::tavily-search
    - inline::code-interpreter
    - inline::rag-runtime
    - remote::model-context-protocol
image_type: conda
