# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the terms described in the LICENSE file in
# the root directory of this source tree.

import json
import logging  # allow-direct-logging
import os

import httpx
import openai
import pytest
from openai import OpenAI

from llama_stack.core.datatypes import AuthenticationRequiredError
from llama_stack.core.library_client import LlamaStackAsLibraryClient
from tests.common.mcp import dependency_tools, make_mcp_server

from .fixtures.test_cases import (
    custom_tool_test_cases,
    file_search_test_cases,
    mcp_tool_test_cases,
    multi_turn_tool_execution_streaming_test_cases,
    multi_turn_tool_execution_test_cases,
    web_search_test_cases,
)
from .helpers import new_vector_store, setup_mcp_tools, upload_file, wait_for_file_attachment
from .streaming_assertions import StreamingValidator


@pytest.mark.parametrize("case", web_search_test_cases)
def test_response_non_streaming_web_search(compat_client, text_model_id, case):
    response = compat_client.responses.create(
        model=text_model_id,
        input=case.input,
        tools=case.tools,
        stream=False,
    )
    assert len(response.output) > 1
    assert response.output[0].type == "web_search_call"
    assert response.output[0].status == "completed"
    assert response.output[1].type == "message"
    assert response.output[1].status == "completed"
    assert response.output[1].role == "assistant"
    assert len(response.output[1].content) > 0
    assert case.expected.lower() in response.output_text.lower().strip()


@pytest.mark.parametrize("case", file_search_test_cases)
def test_response_non_streaming_file_search(
    compat_client, text_model_id, embedding_model_id, embedding_dimension, tmp_path, case
):
    if isinstance(compat_client, LlamaStackAsLibraryClient):
        pytest.skip("Responses API file search is not yet supported in library client.")

    vector_store = new_vector_store(compat_client, "test_vector_store", embedding_model_id, embedding_dimension)

    if case.file_content:
        file_name = "test_response_non_streaming_file_search.txt"
        file_path = tmp_path / file_name
        file_path.write_text(case.file_content)
    elif case.file_path:
        file_path = os.path.join(os.path.dirname(__file__), "fixtures", case.file_path)
        file_name = os.path.basename(file_path)
    else:
        raise ValueError("No file content or path provided for case")

    file_response = upload_file(compat_client, file_name, file_path)

    # Attach our file to the vector store
    compat_client.vector_stores.files.create(
        vector_store_id=vector_store.id,
        file_id=file_response.id,
    )

    # Wait for the file to be attached
    wait_for_file_attachment(compat_client, vector_store.id, file_response.id)

    # Update our tools with the right vector store id
    tools = case.tools
    for tool in tools:
        if tool["type"] == "file_search":
            tool["vector_store_ids"] = [vector_store.id]

    # Create the response request, which should query our vector store
    response = compat_client.responses.create(
        model=text_model_id,
        input=case.input,
        tools=tools,
        stream=False,
        include=["file_search_call.results"],
    )

    # Verify the file_search_tool was called
    assert len(response.output) > 1
    assert response.output[0].type == "file_search_call"
    assert response.output[0].status == "completed"
    assert response.output[0].queries  # ensure it's some non-empty list
    assert response.output[0].results
    assert case.expected.lower() in response.output[0].results[0].text.lower()
    assert response.output[0].results[0].score > 0

    # Verify the output_text generated by the response
    assert case.expected.lower() in response.output_text.lower().strip()


def test_response_non_streaming_file_search_empty_vector_store(
    compat_client, text_model_id, embedding_model_id, embedding_dimension
):
    if isinstance(compat_client, LlamaStackAsLibraryClient):
        pytest.skip("Responses API file search is not yet supported in library client.")

    vector_store = new_vector_store(compat_client, "test_vector_store", embedding_model_id, embedding_dimension)

    # Create the response request, which should query our vector store
    response = compat_client.responses.create(
        model=text_model_id,
        input="How many experts does the Llama 4 Maverick model have?",
        tools=[{"type": "file_search", "vector_store_ids": [vector_store.id]}],
        stream=False,
        include=["file_search_call.results"],
    )

    # Verify the file_search_tool was called
    assert len(response.output) > 1
    assert response.output[0].type == "file_search_call"
    assert response.output[0].status == "completed"
    assert response.output[0].queries  # ensure it's some non-empty list
    assert not response.output[0].results  # ensure we don't get any results

    # Verify some output_text was generated by the response
    assert response.output_text


def test_response_sequential_file_search(
    compat_client, text_model_id, embedding_model_id, embedding_dimension, tmp_path
):
    """Test file search with sequential responses using previous_response_id."""
    if isinstance(compat_client, LlamaStackAsLibraryClient):
        pytest.skip("Responses API file search is not yet supported in library client.")

    vector_store = new_vector_store(compat_client, "test_vector_store", embedding_model_id, embedding_dimension)

    # Create a test file with content
    file_content = "The Llama 4 Maverick model has 128 experts in its mixture of experts architecture."
    file_name = "test_sequential_file_search.txt"
    file_path = tmp_path / file_name
    file_path.write_text(file_content)

    file_response = upload_file(compat_client, file_name, file_path)

    # Attach the file to the vector store
    compat_client.vector_stores.files.create(
        vector_store_id=vector_store.id,
        file_id=file_response.id,
    )

    # Wait for the file to be attached
    wait_for_file_attachment(compat_client, vector_store.id, file_response.id)

    tools = [{"type": "file_search", "vector_store_ids": [vector_store.id]}]

    # First response request with file search
    response = compat_client.responses.create(
        model=text_model_id,
        input="How many experts does the Llama 4 Maverick model have?",
        tools=tools,
        stream=False,
        include=["file_search_call.results"],
    )

    # Verify the file_search_tool was called
    assert len(response.output) > 1
    assert response.output[0].type == "file_search_call"
    assert response.output[0].status == "completed"
    assert response.output[0].queries
    assert response.output[0].results
    assert "128" in response.output_text or "experts" in response.output_text.lower()

    # Second response request using previous_response_id
    response2 = compat_client.responses.create(
        model=text_model_id,
        input="Can you tell me more about the architecture?",
        tools=tools,
        stream=False,
        previous_response_id=response.id,
        include=["file_search_call.results"],
    )

    # Verify the second response has output
    assert len(response2.output) >= 1
    assert response2.output_text

    # The second response should maintain context from the first
    final_message = [output for output in response2.output if output.type == "message"]
    assert len(final_message) >= 1
    assert final_message[-1].role == "assistant"
    assert final_message[-1].status == "completed"


@pytest.mark.parametrize("case", mcp_tool_test_cases)
def test_response_non_streaming_mcp_tool(compat_client, text_model_id, case, caplog):
    if not isinstance(compat_client, LlamaStackAsLibraryClient):
        pytest.skip("in-process MCP server is only supported in library client")

    with make_mcp_server() as mcp_server_info:
        tools = setup_mcp_tools(case.tools, mcp_server_info)

        response = compat_client.responses.create(
            model=text_model_id,
            input=case.input,
            tools=tools,
            stream=False,
        )

        assert len(response.output) >= 3
        list_tools = response.output[0]
        assert list_tools.type == "mcp_list_tools"
        assert list_tools.server_label == "localmcp"
        assert len(list_tools.tools) == 2
        assert {t.name for t in list_tools.tools} == {
            "get_boiling_point",
            "greet_everyone",
        }

        call = response.output[1]
        assert call.type == "mcp_call"
        assert call.name == "get_boiling_point"
        assert json.loads(call.arguments) == {
            "liquid_name": "myawesomeliquid",
            "celsius": True,
        }
        assert call.error is None
        assert "-100" in call.output

        # sometimes the model will call the tool again, so we need to get the last message
        message = response.output[-1]
        text_content = message.content[0].text
        assert "boiling point" in text_content.lower()

    with make_mcp_server(required_auth_token="test-token") as mcp_server_info:
        tools = setup_mcp_tools(case.tools, mcp_server_info)

        exc_type = (
            AuthenticationRequiredError
            if isinstance(compat_client, LlamaStackAsLibraryClient)
            else (httpx.HTTPStatusError, openai.AuthenticationError)
        )
        # Suppress expected auth error logs only for the failing auth attempt
        with caplog.at_level(
            logging.CRITICAL, logger="llama_stack.providers.inline.agents.meta_reference.responses.streaming"
        ):
            with pytest.raises(exc_type):
                compat_client.responses.create(
                    model=text_model_id,
                    input=case.input,
                    tools=tools,
                    stream=False,
                )

        for tool in tools:
            if tool["type"] == "mcp":
                tool["headers"] = {"Authorization": "Bearer test-token"}

        response = compat_client.responses.create(
            model=text_model_id,
            input=case.input,
            tools=tools,
            stream=False,
        )
        assert len(response.output) >= 3


@pytest.mark.parametrize("case", mcp_tool_test_cases)
def test_response_sequential_mcp_tool(compat_client, text_model_id, case):
    if not isinstance(compat_client, LlamaStackAsLibraryClient):
        pytest.skip("in-process MCP server is only supported in library client")

    with make_mcp_server() as mcp_server_info:
        tools = setup_mcp_tools(case.tools, mcp_server_info)

        response = compat_client.responses.create(
            model=text_model_id,
            input=case.input,
            tools=tools,
            stream=False,
        )

        assert len(response.output) >= 3
        list_tools = response.output[0]
        assert list_tools.type == "mcp_list_tools"
        assert list_tools.server_label == "localmcp"
        assert len(list_tools.tools) == 2
        assert {t.name for t in list_tools.tools} == {
            "get_boiling_point",
            "greet_everyone",
        }

        call = response.output[1]
        assert call.type == "mcp_call"
        assert call.name == "get_boiling_point"
        assert json.loads(call.arguments) == {
            "liquid_name": "myawesomeliquid",
            "celsius": True,
        }
        assert call.error is None
        assert "-100" in call.output

        # sometimes the model will call the tool again, so we need to get the last message
        message = response.output[-1]
        text_content = message.content[0].text
        assert "boiling point" in text_content.lower()

        response2 = compat_client.responses.create(
            model=text_model_id, input=case.input, tools=tools, stream=False, previous_response_id=response.id
        )

        assert len(response2.output) >= 1
        message = response2.output[-1]
        text_content = message.content[0].text
        assert "boiling point" in text_content.lower()


@pytest.mark.parametrize("case", mcp_tool_test_cases)
@pytest.mark.parametrize("approve", [True, False])
def test_response_mcp_tool_approval(compat_client, text_model_id, case, approve):
    if not isinstance(compat_client, LlamaStackAsLibraryClient):
        pytest.skip("in-process MCP server is only supported in library client")

    with make_mcp_server() as mcp_server_info:
        tools = setup_mcp_tools(case.tools, mcp_server_info)
        for tool in tools:
            tool["require_approval"] = "always"

        response = compat_client.responses.create(
            model=text_model_id,
            input=case.input,
            tools=tools,
            stream=False,
        )

        assert len(response.output) >= 2
        list_tools = response.output[0]
        assert list_tools.type == "mcp_list_tools"
        assert list_tools.server_label == "localmcp"
        assert len(list_tools.tools) == 2
        assert {t.name for t in list_tools.tools} == {
            "get_boiling_point",
            "greet_everyone",
        }

        approval_request = response.output[1]
        assert approval_request.type == "mcp_approval_request"
        assert approval_request.name == "get_boiling_point"
        assert json.loads(approval_request.arguments) == {
            "liquid_name": "myawesomeliquid",
            "celsius": True,
        }

        # send approval response
        response = compat_client.responses.create(
            previous_response_id=response.id,
            model=text_model_id,
            input=[{"type": "mcp_approval_response", "approval_request_id": approval_request.id, "approve": approve}],
            tools=tools,
            stream=False,
        )

        if approve:
            assert len(response.output) >= 3
            list_tools = response.output[0]
            assert list_tools.type == "mcp_list_tools"
            assert list_tools.server_label == "localmcp"
            assert len(list_tools.tools) == 2
            assert {t.name for t in list_tools.tools} == {
                "get_boiling_point",
                "greet_everyone",
            }

            call = response.output[1]
            assert call.type == "mcp_call"
            assert call.name == "get_boiling_point"
            assert json.loads(call.arguments) == {
                "liquid_name": "myawesomeliquid",
                "celsius": True,
            }
            assert call.error is None
            assert "-100" in call.output

            # sometimes the model will call the tool again, so we need to get the last message
            message = response.output[-1]
            text_content = message.content[0].text
            assert "boiling point" in text_content.lower()
        else:
            assert len(response.output) >= 1
            for output in response.output:
                assert output.type != "mcp_call"


@pytest.mark.parametrize("case", custom_tool_test_cases)
def test_response_non_streaming_custom_tool(compat_client, text_model_id, case):
    response = compat_client.responses.create(
        model=text_model_id,
        input=case.input,
        tools=case.tools,
        stream=False,
    )
    assert len(response.output) == 1
    assert response.output[0].type == "function_call"
    assert response.output[0].status == "completed"
    assert response.output[0].name == "get_weather"


@pytest.mark.parametrize("case", custom_tool_test_cases)
def test_response_function_call_ordering_1(compat_client, text_model_id, case):
    response = compat_client.responses.create(
        model=text_model_id,
        input=case.input,
        tools=case.tools,
        stream=False,
    )
    assert len(response.output) == 1
    assert response.output[0].type == "function_call"
    assert response.output[0].status == "completed"
    assert response.output[0].name == "get_weather"
    inputs = []
    inputs.append(
        {
            "role": "user",
            "content": case.input,
        }
    )
    inputs.append(
        {
            "type": "function_call_output",
            "output": "It is raining.",
            "call_id": response.output[0].call_id,
        }
    )
    response = compat_client.responses.create(
        model=text_model_id, input=inputs, tools=case.tools, stream=False, previous_response_id=response.id
    )
    assert len(response.output) == 1


def test_response_function_call_ordering_2(compat_client, text_model_id):
    tools = [
        {
            "type": "function",
            "name": "get_weather",
            "description": "Get current temperature for a given location.",
            "parameters": {
                "additionalProperties": False,
                "properties": {
                    "location": {
                        "description": "City and country e.g. Bogotá, Colombia",
                        "type": "string",
                    }
                },
                "required": ["location"],
                "type": "object",
            },
        }
    ]
    inputs = [
        {
            "role": "user",
            "content": "Is the weather better in San Francisco or Los Angeles?",
        }
    ]
    response = compat_client.responses.create(
        model=text_model_id,
        input=inputs,
        tools=tools,
        stream=False,
    )
    for output in response.output:
        if output.type == "function_call" and output.status == "completed" and output.name == "get_weather":
            inputs.append(output)
    for output in response.output:
        if output.type == "function_call" and output.status == "completed" and output.name == "get_weather":
            weather = "It is raining."
            if "Los Angeles" in output.arguments:
                weather = "It is cloudy."
            inputs.append(
                {
                    "type": "function_call_output",
                    "output": weather,
                    "call_id": output.call_id,
                }
            )
    response = compat_client.responses.create(
        model=text_model_id,
        input=inputs,
        tools=tools,
        stream=False,
    )
    assert len(response.output) == 1
    assert "Los Angeles" in response.output_text


@pytest.mark.parametrize("case", multi_turn_tool_execution_test_cases)
def test_response_non_streaming_multi_turn_tool_execution(compat_client, text_model_id, case):
    """Test multi-turn tool execution where multiple MCP tool calls are performed in sequence."""
    if not isinstance(compat_client, LlamaStackAsLibraryClient):
        pytest.skip("in-process MCP server is only supported in library client")

    with make_mcp_server(tools=dependency_tools()) as mcp_server_info:
        tools = setup_mcp_tools(case.tools, mcp_server_info)

        response = compat_client.responses.create(
            input=case.input,
            model=text_model_id,
            tools=tools,
        )

        # Verify we have MCP tool calls in the output
        mcp_list_tools = [output for output in response.output if output.type == "mcp_list_tools"]
        mcp_calls = [output for output in response.output if output.type == "mcp_call"]
        message_outputs = [output for output in response.output if output.type == "message"]

        # Should have exactly 1 MCP list tools message (at the beginning)
        assert len(mcp_list_tools) == 1, f"Expected exactly 1 mcp_list_tools, got {len(mcp_list_tools)}"
        assert mcp_list_tools[0].server_label == "localmcp"
        assert len(mcp_list_tools[0].tools) == 5  # Updated for dependency tools
        expected_tool_names = {
            "get_user_id",
            "get_user_permissions",
            "check_file_access",
            "get_experiment_id",
            "get_experiment_results",
        }
        assert {t.name for t in mcp_list_tools[0].tools} == expected_tool_names

        assert len(mcp_calls) >= 1, f"Expected at least 1 mcp_call, got {len(mcp_calls)}"
        for mcp_call in mcp_calls:
            assert mcp_call.error is None, f"MCP call should not have errors, got: {mcp_call.error}"

        assert len(message_outputs) >= 1, f"Expected at least 1 message output, got {len(message_outputs)}"

        final_message = message_outputs[-1]
        assert final_message.role == "assistant", f"Final message should be from assistant, got {final_message.role}"
        assert final_message.status == "completed", f"Final message should be completed, got {final_message.status}"
        assert len(final_message.content) > 0, "Final message should have content"

        expected_output = case.expected
        assert expected_output.lower() in response.output_text.lower(), (
            f"Expected '{expected_output}' to appear in response: {response.output_text}"
        )


@pytest.mark.parametrize("case", multi_turn_tool_execution_streaming_test_cases)
def test_response_streaming_multi_turn_tool_execution(compat_client, text_model_id, case):
    """Test streaming multi-turn tool execution where multiple MCP tool calls are performed in sequence."""
    if not isinstance(compat_client, LlamaStackAsLibraryClient):
        pytest.skip("in-process MCP server is only supported in library client")

    with make_mcp_server(tools=dependency_tools()) as mcp_server_info:
        tools = setup_mcp_tools(case.tools, mcp_server_info)

        stream = compat_client.responses.create(
            input=case.input,
            model=text_model_id,
            tools=tools,
            stream=True,
        )

        chunks = []
        for chunk in stream:
            chunks.append(chunk)

        # Use validator for common streaming checks
        validator = StreamingValidator(chunks)
        validator.assert_basic_event_sequence()
        validator.assert_response_consistency()
        validator.assert_has_tool_calls()
        validator.assert_has_mcp_events()
        validator.assert_rich_streaming()

        # Get the final response from the last chunk
        final_chunk = chunks[-1]
        if hasattr(final_chunk, "response"):
            final_response = final_chunk.response

            # Verify multi-turn MCP tool execution results
            mcp_list_tools = [output for output in final_response.output if output.type == "mcp_list_tools"]
            mcp_calls = [output for output in final_response.output if output.type == "mcp_call"]
            message_outputs = [output for output in final_response.output if output.type == "message"]

            # Should have exactly 1 MCP list tools message (at the beginning)
            assert len(mcp_list_tools) == 1, f"Expected exactly 1 mcp_list_tools, got {len(mcp_list_tools)}"
            assert mcp_list_tools[0].server_label == "localmcp"
            assert len(mcp_list_tools[0].tools) == 5  # Updated for dependency tools
            expected_tool_names = {
                "get_user_id",
                "get_user_permissions",
                "check_file_access",
                "get_experiment_id",
                "get_experiment_results",
            }
            assert {t.name for t in mcp_list_tools[0].tools} == expected_tool_names

            # Should have at least 1 MCP call (the model should call at least one tool)
            assert len(mcp_calls) >= 1, f"Expected at least 1 mcp_call, got {len(mcp_calls)}"

            # All MCP calls should be completed (verifies our tool execution works)
            for mcp_call in mcp_calls:
                assert mcp_call.error is None, f"MCP call should not have errors, got: {mcp_call.error}"

            # Should have at least one final message response
            assert len(message_outputs) >= 1, f"Expected at least 1 message output, got {len(message_outputs)}"

            # Final message should be from assistant and completed
            final_message = message_outputs[-1]
            assert final_message.role == "assistant", (
                f"Final message should be from assistant, got {final_message.role}"
            )
            assert final_message.status == "completed", f"Final message should be completed, got {final_message.status}"
            assert len(final_message.content) > 0, "Final message should have content"

            # Check that the expected output appears in the response
            expected_output = case.expected
            assert expected_output.lower() in final_response.output_text.lower(), (
                f"Expected '{expected_output}' to appear in response: {final_response.output_text}"
            )


@pytest.fixture
def simple_function_tools():
    """Fixture providing simple function tools for testing."""
    return [
        {
            "type": "function",
            "name": "get_weather",
            "description": "Get the weather in a given city",
            "parameters": {
                "type": "object",
                "properties": {
                    "city": {"type": "string", "description": "The city to get the weather for"},
                },
                "required": ["city"],
            },
        },
        {
            "type": "function",
            "name": "get_time",
            "description": "Get the current time",
            "parameters": {
                "type": "object",
                "properties": {
                    "timezone": {"type": "string", "description": "The timezone to get the time for"},
                },
            },
        },
    ]


class TestToolChoiceModes:
    """Test basic tool_choice functionality with different modes and tool types."""

    @pytest.mark.parametrize(
        "tool_choice,expected_has_function_call",
        [
            ("required", True),  # required mode should force tool call
            ("auto", None),  # auto mode lets model decide
            ("none", False),  # none mode should prevent tool calls
        ],
    )
    def test_tool_choice_modes(
        self, compat_client, text_model_id, simple_function_tools, tool_choice, expected_has_function_call
    ):
        """Test different tool_choice modes (required, auto, none)."""
        if not isinstance(compat_client, OpenAI):
            pytest.skip("OpenAI client is required for tool_choice testing")

        response = compat_client.responses.create(
            model=text_model_id,
            input=[
                {
                    "role": "user",
                    "content": "What's the weather in Tokyo?",
                }
            ],
            tools=simple_function_tools,
            tool_choice=tool_choice,
            stream=False,
        )

        function_calls = [output for output in response.output if output.type == "function_call"]

        if expected_has_function_call is True:
            assert len(function_calls) > 0, f"Expected function call with tool_choice='{tool_choice}'"
        elif expected_has_function_call is False:
            assert len(function_calls) == 0, f"Expected no function calls with tool_choice='{tool_choice}'"
        else:  # None means auto - just verify it completes
            assert response.status == "completed"


class TestToolChoiceBuiltinTools:
    """Test tool_choice with built-in tools (web_search, file_search)."""

    def test_tool_choice_web_search(self, compat_client, text_model_id):
        """Test tool_choice with web_search tool."""
        if not isinstance(compat_client, OpenAI):
            pytest.skip("OpenAI client is required for tool_choice testing")

        response = compat_client.responses.create(
            model=text_model_id,
            input=[
                {
                    "role": "user",
                    "content": "What's the latest news about AI?",
                }
            ],
            tools=[{"type": "web_search"}],
            tool_choice={"type": "web_search_preview"},
            stream=False,
        )

        web_search_calls = [output for output in response.output if output.type == "web_search_call"]
        assert len(web_search_calls) > 0, "Expected web_search_call with tool_choice='web_search'"


class TestToolChoiceMCP:
    """Test tool_choice with MCP (Model Context Protocol) tools."""

    # Expected tools available on the MCP server
    EXPECTED_MCP_TOOLS = {"get_boiling_point", "greet_everyone"}

    @pytest.mark.parametrize(
        "tool_choice_config,expected_tool_name",
        [
            ({"type": "mcp", "server_label": "localmcp"}, None),  # Server-level selection
            (
                {"type": "mcp", "server_label": "localmcp", "name": "get_boiling_point"},
                "get_boiling_point",
            ),  # Specific tool
        ],
    )
    def test_tool_choice_mcp(self, compat_client, text_model_id, tool_choice_config, expected_tool_name):
        """Test tool_choice with MCP tools (server-level and specific tool)."""
        # if not isinstance(compat_client, LlamaStackAsLibraryClient):
        #     pytest.skip("in-process MCP server is only supported in library client")

        with make_mcp_server() as mcp_server_info:
            tools = [
                {
                    "type": "mcp",
                    "server_label": "localmcp",
                    "server_url": mcp_server_info["server_url"],
                }
            ]

            response = compat_client.responses.create(
                model=text_model_id,
                input=[
                    {
                        "role": "user",
                        "content": "What is the boiling point of myawesomeliquid? You MUST call the tool.",
                    }
                ],
                tools=tools,
                tool_choice=tool_choice_config,
                stream=False,
            )

            # Verify MCP list tools output contains expected tools
            mcp_list_tools = [output for output in response.output if output.type == "mcp_list_tools"]
            assert len(mcp_list_tools) == 1, "Expected exactly one mcp_list_tools output"
            assert mcp_list_tools[0].server_label == "localmcp"

            # Verify the tools listed match our expected tools
            actual_tool_names = {tool.name for tool in mcp_list_tools[0].tools}
            assert actual_tool_names == self.EXPECTED_MCP_TOOLS, (
                f"MCP server tools mismatch. Expected {self.EXPECTED_MCP_TOOLS}, got {actual_tool_names}"
            )

            # Verify MCP calls were made
            mcp_calls = [output for output in response.output if output.type == "mcp_call"]
            assert len(mcp_calls) > 0, f"Expected MCP call with tool_choice={tool_choice_config}"

            # Verify all MCP calls come from the server's tool list
            for mcp_call in mcp_calls:
                assert mcp_call.name in self.EXPECTED_MCP_TOOLS, (
                    f"MCP call '{mcp_call.name}' is not in the server's tool list: {self.EXPECTED_MCP_TOOLS}"
                )

            # If a specific tool was requested, verify it was called
            if expected_tool_name:
                assert mcp_calls[0].name == expected_tool_name, (
                    f"Expected {expected_tool_name}, got {mcp_calls[0].name}"
                )


class TestToolChoiceAllowedTools:
    """Test tool_choice with allowed_tools filtering."""

    @pytest.mark.parametrize(
        "allowed_tools_config",
        [
            # Single function tool
            {
                "type": "allowed_tools",
                "tools": [{"type": "function", "name": "get_weather"}],
                "mode": "required",
            },
            # Multiple function tools
            {
                "type": "allowed_tools",
                "tools": [{"type": "function", "name": "get_weather"}, {"type": "function", "name": "get_time"}],
                "mode": "auto",
            },
        ],
    )
    def test_tool_choice_allowed_tools_function(
        self, compat_client, text_model_id, simple_function_tools, allowed_tools_config
    ):
        """Test tool_choice with allowed_tools filtering."""
        if not isinstance(compat_client, OpenAI):
            pytest.skip("OpenAI client is required for tool_choice testing")

        response = compat_client.responses.create(
            model=text_model_id,
            input=[
                {
                    "role": "user",
                    "content": "Get some information",
                }
            ],
            tools=simple_function_tools,
            tool_choice=allowed_tools_config,
            stream=False,
        )

        # Verify response completes
        assert response.status == "completed"

        function_calls = [output for output in response.output if output.type == "function_call"]
        # If mode is required, verify we got a function call
        if allowed_tools_config["mode"] == "required":
            assert len(function_calls) > 0, "Expected function call with mode='required'"

        if len(function_calls) > 0:
            # Verify it's one of the allowed tools
            allowed_names = [tool["name"] for tool in allowed_tools_config["tools"]]
            assert function_calls[0].name in allowed_names

    def test_tool_choice_allowed_tools_mixed(self, compat_client, text_model_id):
        """Test tool_choice with mixed tool types in allowed_tools."""
        if not isinstance(compat_client, OpenAI):
            pytest.skip("OpenAI client is required for tool_choice testing")

        tools = [
            {
                "type": "function",
                "name": "get_weather",
                "description": "Get the weather",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "city": {"type": "string"},
                    },
                },
            },
            {"type": "web_search"},
        ]

        response = compat_client.responses.create(
            model=text_model_id,
            input=[
                {
                    "role": "user",
                    "content": "Find information",
                }
            ],
            tools=tools,
            tool_choice={
                "type": "allowed_tools",
                "tools": [{"type": "function", "name": "get_weather"}, {"type": "web_search_preview"}],
                "mode": "auto",
            },
            stream=False,
        )

        assert response.status == "completed"

    def test_tool_choice_allowed_tools_mcp(self, compat_client, text_model_id):
        """Test tool_choice with MCP tools in allowed_tools."""
        # if not isinstance(compat_client, LlamaStackAsLibraryClient):
        #     pytest.skip("in-process MCP server is only supported in library client")

        with make_mcp_server() as mcp_server_info:
            tools = [
                {
                    "type": "mcp",
                    "server_label": "localmcp",
                    "server_url": mcp_server_info["server_url"],
                }
            ]

            response = compat_client.responses.create(
                model=text_model_id,
                input=[
                    {
                        "role": "user",
                        "content": "What is the boiling point of myawesomeliquid?",
                    }
                ],
                tools=tools,
                tool_choice={
                    "type": "allowed_tools",
                    "tools": [{"type": "mcp", "server_label": "localmcp"}],
                    "mode": "required",
                },
                stream=False,
            )

            mcp_calls = [output for output in response.output if output.type == "mcp_call"]
            assert len(mcp_calls) > 0, "Expected MCP call with allowed_tools MCP server"


class TestToolChoiceEdgeCases:
    """Test edge cases and error conditions."""

    @pytest.mark.parametrize(
        "tools,tool_choice",
        [
            ([], "required"),  # No tools with required mode
            ([], "auto"),  # No tools with auto mode
        ],
    )
    def test_tool_choice_without_tools(self, compat_client, text_model_id, tools, tool_choice):
        """Test tool_choice when no tools are provided."""
        if not isinstance(compat_client, OpenAI):
            pytest.skip("OpenAI client is required for tool_choice testing")

        response = compat_client.responses.create(
            model=text_model_id,
            input=[
                {
                    "role": "user",
                    "content": "Hello!",
                }
            ],
            tools=tools,
            tool_choice=tool_choice,
            stream=False,
        )

        # Should complete (tool_choice should be ignored when no tools available)
        assert response.status in ["completed", "incomplete"]
        function_calls = [output for output in response.output if output.type == "function_call"]
        assert len(function_calls) == 0

    def test_tool_choice_invalid_tool_name(self, compat_client, text_model_id, simple_function_tools):
        """Test tool_choice with invalid tool name (should be handled gracefully)."""
        if not isinstance(compat_client, OpenAI):
            pytest.skip("OpenAI client is required for tool_choice testing")

        response = compat_client.responses.create(
            model=text_model_id,
            input=[
                {
                    "role": "user",
                    "content": "What's the weather?",
                }
            ],
            tools=simple_function_tools,
            tool_choice={"type": "function", "name": "nonexistent_tool"},
            stream=False,
        )

        # Should still complete (invalid tool_choice should be ignored with warning)
        assert response.status in ["completed", "incomplete"]
        function_calls = [output for output in response.output if output.type == "function_call"]
        assert len(function_calls) == 0


class TestToolChoiceMultipleTools:
    """Test tool_choice with multiple tools of different types."""

    @pytest.mark.parametrize(
        "tool_choice,expected_type",
        [
            ({"type": "function", "name": "calculate"}, "function_call"),
            ({"type": "web_search_preview"}, "web_search_call"),
        ],
    )
    def test_tool_choice_mixed_tools(self, compat_client, text_model_id, tool_choice, expected_type):
        """Test tool_choice when both function and web_search tools are available."""
        if not isinstance(compat_client, OpenAI):
            pytest.skip("OpenAI client is required for tool_choice testing")

        tools = [
            {
                "type": "function",
                "name": "calculate",
                "description": "Perform calculations",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "expression": {"type": "string"},
                    },
                },
            },
            {"type": "web_search"},
        ]

        content = "Calculate 2 + 2" if expected_type == "function_call" else "Search for AI news"

        response = compat_client.responses.create(
            model=text_model_id,
            input=[
                {
                    "role": "user",
                    "content": content,
                }
            ],
            tools=tools,
            tool_choice=tool_choice,
            stream=False,
        )

        # Should call the expected tool type
        matching_calls = [output for output in response.output if output.type == expected_type]
        assert len(matching_calls) > 0, f"Expected {expected_type} with tool_choice={tool_choice}"

    def test_tool_choice_required_multiple_functions(self, compat_client, text_model_id):
        """Test tool_choice='required' with multiple function tools."""
        if not isinstance(compat_client, OpenAI):
            pytest.skip("OpenAI client is required for tool_choice testing")

        tools = [
            {
                "type": "function",
                "name": "get_weather",
                "description": "Get weather",
                "parameters": {
                    "type": "object",
                    "properties": {"city": {"type": "string"}},
                },
            },
            {
                "type": "function",
                "name": "get_time",
                "description": "Get time",
                "parameters": {
                    "type": "object",
                    "properties": {"timezone": {"type": "string"}},
                },
            },
            {
                "type": "function",
                "name": "calculate",
                "description": "Calculate",
                "parameters": {
                    "type": "object",
                    "properties": {"expr": {"type": "string"}},
                },
            },
        ]

        response = compat_client.responses.create(
            model=text_model_id,
            input=[
                {
                    "role": "user",
                    "content": "Help me with something",
                }
            ],
            tools=tools,
            tool_choice="required",
            stream=False,
        )

        # Should call one of the available functions
        function_calls = [output for output in response.output if output.type == "function_call"]
        assert len(function_calls) > 0
        # Verify it's one of the available functions
        assert function_calls[0].name in ["get_weather", "get_time", "calculate"]
