name: Installer CI

on:
  pull_request:
    paths:
      - 'install.sh'
  push:
    paths:
      - 'install.sh'
  schedule:
    - cron: '0 2 * * *'  # every day at 02:00 UTC

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bash syntax check
        run: bash -n install.sh

  smoke-test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run installer end-to-end
        run: ./install.sh
      - name: Wait for health endpoint
        run: |
          timeout 120 bash -c \
            'until curl -fsS http://localhost:8321/v1/health; do sleep 1; done'
