name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'
      - '.github/workflows/publish-helm.yml'
jobs:
  publish-helm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and Push Helm Chart
        run: | # Version is either git tag or git hash
          if [[ $GITHUB_REF_TYPE == "tag" ]]; then
            VERSION=$(git describe --tags --abbrev=0 | sed 's/^v//')
          elif [[ $GITHUB_REF_TYPE == "branch" ]]; then
            VERSION="0.0.0-$(git rev-parse --short HEAD)"
          fi
          helm package chart --version $VERSION
          helm push llama-stack-${VERSION}.tgz oci://ghcr.io/${GITHUB_REPOSITORY,,}
