name: Check semantic PR titles

run-name: Ensure that PR titles follow the conventional commit spec

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title's semantic conformance
        uses: amannn/action-semantic-pull-request@7f33ba792281b034f64e96f4c0b5496782dd3b37 # v6.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
